dims clean version, worked on checking ./matrix not being the only file. It works

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -6,16 +6,7 @@
 # Last Modified: January 13, 2020
 
 # Debugger mode
-set -x
-#set -v
-
-
-#
-main() {
-    echo -e "(main) 1 = $1"
-    echo -e "(main) 2 = $2"
-    operations $1 $2
-}
+#set -x
 
 
 #
@@ -26,29 +17,15 @@ ls
 }
 
 
-#
-pathFinding() {
-
-ls
-
-}
-
 #@param: $1 - the name of the operations
 #
 operations() {
     local flag=0;
     local fileFlag=0
     local argsFlag=0
-#    echo -e "param 1 in operations = $1" ##########################################
-#    echo -e "param 0 = $0" #####################################################
     # check argument count
     local opArgs=2  # the expected amount of arguments for dims, transpose, and mean operations
-    #######################local argCount=$#
-#    echo -e "(operations) actual arg count = $numOfArgs"
-#    echo -e "(operations) expected arg count = $opArgs"
     # check if file is readable
-#    echo -e "datafilepath = $datafilepath"
-#    echo -e "argument 2 is $2"
     fileIsReadable
     fileFlag=$?
     if [ $1 = "add" -o $1 = "multiply" ]
@@ -78,7 +55,6 @@ operations() {
 #
 fileIsReadable() {
     # test if file exist and it's readable
-    #echo -e "(fileIsReadable) This is the file: $1" #######################################################
     local checkSecondFile=0
     if [ -e "$datafilepath" ]
     then
@@ -124,9 +100,9 @@ checkArgCount() {
     if [ $1 -lt $2 ]
     then
         return 1
-    elif [ $1 -gt $2 ]
+    elif [ $numOfArgs = 0 ]
     then
-        echo "Argument count is less than the required number of arguments" 1>&2
+        echo "Error: Operation has not arguments" 1>&2
         exit 1
     fi
     return 0
@@ -137,15 +113,12 @@ checkArgCount() {
 stdinOps() {
 ls
 
-
-
 }
 
 
 #  may not use this
 otherOps() {
 ls
-
 
 }
 
@@ -177,8 +150,6 @@ showDims() {
 transpose () {
 ls
 
-
-
 }
 
 
@@ -191,14 +162,7 @@ cols=0
 numOfArgs="$#"
 
 
-# handle any errors that effects the script as a whole:
-# ./matrix or matrix cannot be the last argument
-# the matrix file is readable
 # generate path of file via stdin or a file
-
-
-#if [ "$#" -lt "3" ]
-#then
 if [ "$numOfArgs" = "1" ]
 then
     cat > "$datafilepath"
@@ -210,12 +174,7 @@ then
         matrixB=$3
     fi
 fi
-#fi
-
-# echo  -e "The argument count of the script: $#"
-
-# main $1 $2
-
+# run dims, transpose, mean, add, or multiply
 operations $1 
     
 
